spring:
  datasource:
    url: ${UNI_DATABASE:jdbc:mysql://localhost:3306/unieventos?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    username: ${UNI_USER:}
    password: ${UNI_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: UniEventos
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:}
  jpa:
    hibernate:
      ddl-auto: validate

server:
  port: ${UNI_PORT:8080}
  servlet:
    context-path: /unieventos

unieventos:
  email:
    apikey: ${EMAIL_API_KEY:}
    apiurl: ${EMAIL_API_URL}
    from: ${EMAIL_FROM}
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

 

