name: Docker CD

on:
  workflow_run:
    workflows: ["Docker CI"] # Nome do seu workflow de CI
    types: [completed]

jobs:
  deploy:
    name: Deploy na Máquina Remota
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Fazer checkout do código
        uses: actions/checkout@v3

      - name: Configurar SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Remover containers antigos
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "sudo docker compose -f ${{ secrets.COMPOSE_FILE_PATH }} down"

      - name: Puxar a nova imagem Docker
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "sudo docker pull ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:2.00"

      - name: Subir a nova aplicação
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "sudo docker compose -f ${{ secrets.COMPOSE_FILE_PATH }} up -d"
